var express = require('express');
var controller = require('./index.controller');
var auth = require('../../auth.service');
var router = express.Router();
var multipart = require('connect-multiparty');
var multipartMiddleware = multipart();
router.put('/me',[auth.isAuthenticated(),multipartMiddleware], controller.updateUser);
router.put('/update/profile',[auth.isAuthenticated(),multipartMiddleware], controller.updateUserasAdmin);
router.post('/login',controller.login);
router.get('/',controller.allUsers);
router.get('/model/all', controller.allUsers);
router.delete('/:id',auth.isAdmin(),controller.deleteUser);
router.put('/delete',auth.isAdmin(),controller.deleteUsers);
router.get('/active/:id',auth.isAdmin(),controller.active);
router.get('/de-active/:id',auth.isAdmin(),controller.deActive);
router.put('/de-active',auth.isAdmin(),controller.deActiveList);
router.put('/active',auth.isAdmin(),controller.activeList);
router.put('/me/change-password',auth.isAuthenticated(),controller.changePassword);
router.put('/change-password',auth.isAdmin(),controller.changePasswordasAdmin);
router.put('/update/profile',[auth.isAdmin(),multipartMiddleware], controller.updateUserasAdmin);
module.exports = router;
