var express = require('express');
var controller = require('./index.controller');
var auth = require('../../auth.service');
var router = express.Router();
var multipart = require('connect-multiparty');
var multipartMiddleware = multipart();
router.get('/:id',controller.getDetail);
router.post('/register', controller.register);
router.put('/register', auth.isAdmin(),controller.registerByAdmin);
router.put('/register/model',[multipartMiddleware], controller.registerModel);
router.get('/me/info',[auth.isAuthenticated()],controller.me);
router.put('/me',[auth.isAuthenticated(),multipartMiddleware], controller.updateUser);
router.get('/info/:id', auth.getDataLogin(),controller.getInfoUser);
router.post('/login',controller.login);
router.get('/',controller.allUsers);
router.get('/model/all', controller.allUsers);
router.delete('/:id',auth.isAdmin(),controller.deleteUser);
router.put('/delete',auth.isAdmin(),controller.deleteUsers);
router.put('/:id/subscribe',auth.isAuthenticated(), controller.subscribe );
router.post('/forget-password',controller.forgetPassword);
router.get('/active/:id',auth.isAdmin(),controller.active);
router.get('/de-active/:id',auth.isAdmin(),controller.deActive);
router.put('/de-active',auth.isAdmin(),controller.deActiveList);
router.put('/active',auth.isAdmin(),controller.activeList);
router.put('/me/change-password',auth.isAuthenticated(),controller.changePassword);
router.put('/change-password',auth.isAdmin(),controller.changePasswordasAdmin);
module.exports = router;
