export * from './alert.service';
//export * from './authentication.service';
export * from './user.service';
export * from './model.service';
export * from './xtalk-notification.service';
export * from './review.service';
// export * from './call.service';
// export * from './chat.service';
export * from './acceptCall.service';
export * from './withdraws.service';
export * from './bank.service';
export * from './pageconfig.service';
export * from './search.service';
export * from './mygallery.service';
export * from './Ads.service';
//export * from './socket.service';
export * from './seoconfig.service';
export * from './loading-service.service';
// export * from './localstorage.service';