var express = require('express');
var controller = require('./index.controller');
var auth = require('../../auth.service');
var router = express.Router();
var multipart = require('connect-multiparty');
var multipartMiddleware = multipart();
router.put('/',[multipartMiddleware,auth.isAdmin()],controller.postAds);
router.put('/active/:id',auth.isAdmin(),controller.putActive);
router.get('/de-active/:id',auth.isAdmin(),controller.putDeactive);
router.delete('/:id',auth.isAdmin(),controller.deleteAds);
router.get('/',auth.isAdmin(),controller.getAds);
module.exports=router;